const CODIO_EDITOR_CHANGED = 'editor';
const CODIO_SELECTION_CHANGED = 'selection';
const CODIO_TEXT_CHANGED = 'text';
const CODIO_VISIBLE_RANGE_CHANGED = 'visibleRange';
const CODIO_EXEC = 'exec';

export { CODIO_EDITOR_CHANGED, CODIO_SELECTION_CHANGED, CODIO_TEXT_CHANGED, CODIO_VISIBLE_RANGE_CHANGED, CODIO_EXEC };
